//UN COMPONENTE ES UNA FUNCION (SI SE HABLA DE COMPONENETES FUNCIONALES) QUE PUEDE O NO EJECUTAR UNA LOGICA PERO SIEMPRE O CASI SIEMPRE DEBE DEVOLVER ELEMENTOS QUE PUEDAN REFLEJARSE EN LA PANTALLA

//COMPONENTE DE TIPO CLASE (YA NO SE RECOMIENDA UTILIZARLOS PERO AUN SE SIGUEN IMPLEMENTANDO EN LA ACTUALIDAD)

import React, { Component } from 'react'
import PropsClass from './PropsClass'
class HelloWordClass extends Component {
  //COMO MI COMPONENTE HelloWordClass HEREDA DE Component, DEBO UTILIZAR super PARA PODER PASAR PROPIEDADES (PROPS) ENTRE COMPONENTES Y ENTREGRASELOS AL CONSTRUCTOR
  constructor(props){
    super(props)
  }
  render() {
    // AQUI SE HACE DECLARACION DE VARIABLES, FUNCIONES, OBJETOS, ARRAYS ETC...
    return (
      <>
      <PropsClass name={this.props.name}/>
      </>
    )
  }
}

export default HelloWordClass
